### PR TITLE
Remove unused babel-runtime

### PR DESCRIPTION
**Pull request by XVincentX**

### CODE REVIEW

**Comment by pksunkara** [comment]
We needed that if I remember according to @danielgtaylor. Let's check once with him.

**Comment by danielgtaylor** [comment]
@XVincentX @pksunkara it was required for generators or looping or something, but I'm not 100% sure anymore. I will look into this and see if it's still required or if we changed the underlying implementation.

**Comment by XVincentX** [comment]
I think you're still using them, but it's a devDependency since the published version (`lib`) is es5 transpiled.

**Comment by danielgtaylor** [comment]
@XVincentX I don't think we can remove this like you have done. When this module is being transpiled into ES5, it is [using the `runtime` option](https://github.com/danielgtaylor/peasant/blob/master/index.js#L150) that generates ES5 that assumes the runtime module is available. It prevents copying a bunch of crap into the top of each generated source file by keeping all the common functionality in the Babel runtime module and just importing it instead.

Try this with your change, for example: `npm uninstall babel-runtime && npm run prepublish`

So, if this is a big problem for you, then we need to make it possible for Peasant to compile without this module, set that option, then remove the module and make a release. It's a really light module and makes debugging the generated ES5 js files a bit easier, so I'd prefer to keep it if possible, but I'm open to removing it.

cc @pksunkara

**Comment by XVincentX** [comment]
I am sure we can safely remove this module. Please leave the PR open, I will polish it and some commits to make it happen.

**Comment by pksunkara** [comment]
@danielgtaylor But, we can still move it to a devDependency.

**Comment by XVincentX** [comment]
@pksunkara That is my point ;)

**Comment by danielgtaylor** [comment]
@pksunkara @XVincentX this is the top of the transpiled `lib/parse-result.js`:

```js
/*
 * Parse result-specific refract elements.
 *
 * General structure:
 *
 * + ParseResult
 *   + Annotation
 */

'use strict';

var _get = require('babel-runtime/helpers/get')['default'];

var _inherits = require('babel-runtime/helpers/inherits')['default'];

var _createClass = require('babel-runtime/helpers/create-class')['default'];

var _classCallCheck = require('babel-runtime/helpers/class-call-check')['default'];

var _interopRequireDefault = require('babel-runtime/helpers/interop-require-default')['default'];
```

We need to change how this module is compiled, we can't just move `babel-runtime` to a dev dep!

**Comment by pksunkara** [comment]
Ah, Thanks @danielgtaylor. That was what I was wondering.

**Comment by kylef** [comment]
@XVincentX I'm going to close this out since there's not been much activity in this PR. `babel-runtime` is a runtime dependency and not a development dependency, and as such it must be a runtime dependency. See https://babeljs.io/docs/plugins/transform-runtime/ for more information. 

screen shot 2016-05-24 at 08 15 57


If you're having problems with there being the babel runtime. Please let us know.

**Pull request closed without merging**
